version: '2'

services:
  db:
    image: postgres:9.4
    volumes:
      - /home/ubuntu/export:/export
    environment:
      - PGDATA=/export/pgdata
    container_name: db
    restart: always

  icat:
    environment:
      - POSTGRES_SERVER=db
      - ICAT_PLUGIN=1.8
      - EXPORT=/export
    build:
      context: ./icat
      args:
        - ICAT_PLUGIN=1.8
    links:
      - db:db
    container_name: icat
    devices:
      - /dev/urandom:/dev/random
    volumes_from:
      - db:rw
    hostname: icat
    ports:
      - 0.0.0.0:1247:1247
    restart: always

  idrop:
    build:
      context: ./idrop-web2-tomcat7
    links:
      - icat:icat
    devices:
      - /dev/urandom:/dev/random
    volumes_from:
      - icat:ro
    container_name: idrop
    hostname: idrop
    restart: always

  web:
    build:
      context: ./apache2-proxy
    links:
      - idrop:idrop
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes_from:
      - icat:ro
    container_name: web
    hostname: web
    restart: always

  resource1:
    environment:
      - EXPORT=/expat
    build:
      context: ./icat
    links:
      - icat:icat
    container_name: iresc1
    devices:
      - /dev/urandom:/dev/random
    volumes:
      - /home/ubuntu/expat:/expat
    volumes_from:
      - icat:ro
    hostname: iresc1
    restart: always
