version: '2'

services:
  db:
    image: postgres:9.4
    volumes:
      - /home/ubuntu/export/:/var/lib/postgresql/data/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: db

  icat:
    environment:
      - POSTGRES_SERVER=db
    build:
      context: ./icat
      dockerfile: Dockerfile.418
    links:
      - db:db
    container_name: icat
    devices:
      - /dev/urandom:/dev/random
    volumes:
      - /home/ubuntu/export:/export
    hostname: icat

  idrop:
    build:
      context: ./idrop-web2-tomcat7
    links:
      - icat:icat
    devices:
      - /dev/urandom:/dev/random
    container_name: idrop
    hostname: idrop

  web:
    build:
      context: ./apache2-proxy
    links:
      - idrop:idrop
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes_from:
      - icat:ro
    container_name: web
    hostname: web
